apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-helloworld
  name: go-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-helloworld
  template:
    metadata:
      labels:
        app: go-helloworld
    spec:
      containers:
        - image: ghcr.io/2022-4400-exp/4418-go-helloworld-2:6522c0795c1658b9d19d6e98b89d5a6882202df7
          name: go-helloworld
